platform :ios, '12.0'

target 'LynxTemplate' do
  use_frameworks!

  pod 'Lynx',                '3.6.0', :subspecs => ['Framework']
  pod 'PrimJS',              '3.6.1', :subspecs => ['quickjs', 'napi']
  pod 'LynxService',         '3.6.0', :subspecs => ['Image', 'Log', 'Http']
  pod 'SDWebImage',          '5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      c.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
    end
  end
end
