name: LynxTemplate
options:
  bundleIdPrefix: com.example
  deploymentTarget:
    iOS: '12.0'
settings:
  base:
    SWIFT_VERSION: '5.9'
    ENABLE_USER_SCRIPT_SANDBOXING: 'NO'
targets:
  LynxTemplate:
    type: application
    platform: iOS
    sources:
      - path: LynxTemplate
    info:
      path: LynxTemplate/Info.plist
      properties:
        CFBundleDisplayName: LynxTemplate
        CFBundleShortVersionString: '0.0.1'
        CFBundleVersion: '1'
        UILaunchStoryboardName: ''
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        NSAppTransportSecurity:
          NSAllowsLocalNetworking: true
          NSExceptionDomains:
            localhost:
              NSTemporaryExceptionAllowsInsecureHTTPLoads: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.lynxtemplate
        TARGETED_DEVICE_FAMILY: '1,2'
    dependencies: []
